### ISSUE TITLE
arch.flags vs CFLAGS

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd-lib-builder#5] opened 2015-10-29 11:41 UTC
i just noticed that `arch.flags` will prevail even when i pass `CFLAGS` to the build:

     $ make CFLAGS="-g -O2"

will still contain `-march=core2 -mfpmath=sse -msse -msse2`, which is contrary to what i would expect, as these architecture specific flags are not strictly needed to produce a valid build (and i would argue that they are rather optimization flags).

I understand that it is easy to add another `arch.flags=""` to make call to *make*, but i think the current behaviour does not follow [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by electrickery** [comment] 2015-10-29 18:04
On 2015-10-29 12:41 PM, umläute wrote:
> i just noticed that |arch.flags| will prevail even when i pass |CFLAGS|
> to the build:
> 
> |$ make CFLAGS="-g -O2" |
> 
> will still contain |-march=core2 -mfpmath=sse -msse -msse2|, which is
> contrary to what i would expect, as these architecture specifc flags are
> not strictly needed to produce a valid build (and i would argue that
> they are rather optimization flags).

The idea might have been that in the context of Pd-externals, you should
always want optimization flags, assuming they maximize performance. I
know this is an important goal for Pd-lib-builder.

But even so, this should be documented somewhere in the main Makefile.
> 
> I understand that it is easy to add another |arch.flags=""|, but i think
> the decision does not follow POLA
> <https://en.wikipedia.org/wiki/Principle_of_least_astonishment>.

Not optimizing in DSP software would be astonishing :-).

**Comment by umlaeute** [comment] 2015-10-29 19:28
no optimization by default would indeed be astonishing.

i'm talking specifically about overriding any optimization flags.

from the Makefile.pdbuilder:

    # CFLAGS:
    # Compiler (notably optimization) flags which are defined by 
    # Makefile.pdlibbuilder, but may be overriden via command argument.

**Comment by katjav** [comment] 2015-10-30 01:32
True, all optimization flags should be overridable by CFLAGS so it isn't done correctly in Makefile.pdlibbuilder. 

I had classified -f flags as optimization flags and -m flags as architecture flags .The -m flags tune asm code to specific architecture and in many cases that means optimization. But -m flags like -mfloat-abi=hard, -mmacosx-version-min=10.4, are about compatibility rather than optimization. Also some -m flags are needed in the linking process. Not all -m flags should be overridable by CFLAGS, so the category must be subdivided somehow.

**Comment by umlaeute** [comment] 2015-10-30 18:11
but even the *compatibility* flags are not strictly necessary: any decent compiler will produce binaries that are compatible with the system used for building.

and adding compat-flags like `-mmacosx-version-min=10.4` might not be desirable in special situations.
(again we are not speaking of *defaults*, but about *overriding defaults*)

**Comment by katjav** [comment] 2015-10-31 21:02
Would you suggest to make all flags in 'arch.flags' overridable by CFLAGS?

**Comment by umlaeute** [comment] 2015-10-31 21:06
i think i know understand better what you mean:

since the `arch.flags` are *also* used in the linking stage, disabling them in the compiler (only) by overriding the `CFLAGS` might break the build (and the only fix is to (un)set the `arch.flags` for the the linker stage; but if we do that then we have also (automatically) disabled them in the compiler stage even if they don't override them via `CFLAGS`).

which makes me think of `LDFLAGS`, which unfortunately seems to be currently unsupported (#6)

**Comment by umlaeute** [comment] 2015-10-31 21:08
as for the question about overriding all flags in `arch.flags`: yes, i think that `CFLAGS` should be able to override all compiler flags not strictly necessary for building.

**Comment by umlaeute** [comment] 2015-10-31 21:10
and please keep in mind that this is my personal opinion (I don't have any authoritative references that would support my view; it just feels right that way :-))

**Comment by katjav** [comment] 2015-10-31 21:46
I've been fiddling a long time with the classification of flags because the gcc manual doesn't distinguish by build stage 'preprocessor', 'compiler', 'linker' like you use them in a makefile. Instead it is grouped by 'type':

https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html

In practice I found that architecture dependent flags (some but not all) must be given to compiler and linker. I made this category 'arch.flags' to avoid duplicate listings. In retrospect this wasn't such a good idea and it would be better to just define categories for preprocessor flags, compiler flags and linker flags, and adding flags to multiple categories whenever needed. Then I could follow regular naming conventions and support CPPFLAGS and LDFLAGS as well. Hopefully this can be refactored without breaking compatibility.

**Comment by umlaeute** [comment] 2015-10-31 22:55
so why can't you have `arch.flags` be added to both `CFLAGS` and `LDFLAGS`?

if somebody wanted to override only the *architecture flags*, they could do so by specifying `arch.flags`.
if someone wanted to fuddle with `CFLAGS` and `LDFLAGS` they can do so as well

**Comment by katjav** [comment] 2015-11-03 11:47
Sorry, I'm still puzzling on this topic. Classifying the arch.flags as both CFLAGS and LDFLAGS might work as a quick fix. But I don't like that Makefile.pdlibbuilder passes flags in a build stage where they are irrelevant. It doesn't break the builds, but rather than making quick fixes on top of this flaw, I'd like to sort it out better.

The point is that flags or options must be classified in so many ways:

1. per hardware architecture
2. per operating system
3. per language (C, C++)
4. per necessity (indispensable / not indispensable for the build)
4. per origin (Makefile.pdlibbuilder, including Makefile, command line, environment)
5. per build stage (preprocessor / compiler, linker)

Hardware architecture and operating system can together be called 'platform'. Some platform-dependent options are indispensable for the build and therefore classified directly under c.flags / c.ldflags / c.ldlibs and their cxx equivalents. Other platform-dependent options are set as Makefile.pdlibbuilder defaults to tune the build to target platform(s) with binary distributions in mind. Such options are classified under arch.flags, and they comprise -m options and in the Darwin case also -arch options. 

The arch.flags are passed directly to compiler and linker in the rules, which is not good because: 
1. they are not indispensable, yet aren't overriden by standard GNU flags
2. some flags are passed to build stages where they are irrelevant 

The solution to both issues could be to sub-classify them in the platform-dependent variable defaults, and then include them in CFLAGS and LDFLAGS respectively, instead of passing directly in the rule commands. Most arch.flags are compiler flags but IIRC some are (also) intended for the linker. I need to find unambiguous info about this in the GCC docs to do this reorganisation (rather than find out by trial and error).

As a side note, 'arch.flags' isn't really an appropriate variable name after all. In GCC docs the -m options are listed under entries in 'Hardware Models and Configurations' where the 'm' seems to refer to 'machine':

https://gcc.gnu.org/onlinedocs/gcc/Submodel-Options.html#Submodel-Options

But (for example) hardware model 'Darwin' and option '-mmacosx-version-min=10.4' are about specific hardware-OS combinations. Therefore it may be more appropriate to speak in terms of 'target platforms' when referring to hardware-OS combinations and build flags for these. Makefile.pdlibbuilder doesn't currently distinguish explicitly between build platform and target platform. But it should do that, and eventually it should facilitate cross-platform building in a user friendly way.

**Comment by umlaeute** [comment] 2015-11-03 11:57
On 11/03/2015 12:47 PM, Katja Vetter wrote:
> The solution to both issues could be to sub-classify them in the platform-dependent variable defaults, and then include them in CFLAGS and LDFLAGS respectively, instead of passing directly in the rule commands.

this is what i had in mind.

> Most arch.flags are compiler flags but IIRC some are (also) intended for the linker.

to avoid passing irrelevant (though thankfully ignored) flags to a
stage, how about "c.arch.flags" and "ld.arch.flags" (or "arch.c.flags"...)?

**Comment by umlaeute** [comment] 2015-11-03 12:00
On 11/03/2015 12:47 PM, Katja Vetter wrote:
> As a side note, 'arch.flags' isn't really an appropriate variable name after all.

i think it is a quite good name for architecture (which i understand as
"hardware"¹) specific flags.
> 
> But (for example) hardware model 'Darwin' and option '-mmacosx-version-min=10.4' are about specific hardware-OS combinations. Therefore it may be more appropriate to speak in terms of 'target platforms' when referring to hardware-OS combinations and build flags for these. Makefile.pdlibbuilder doesn't currently distinguish explicitly between build platform and target platform. But it should do that, and eventually it should facilitate cross-platform building in a user friendly way.
> 

fwiiw, "Darwin" is *not* a hardware model but the core OS (upon which
OSX builds)

**Comment by katjav** [comment] 2015-11-03 14:36
The 'arch.flags' in Makefile.pdlibbuilder are set per hardware-OS combination. If we call a hardware-OS combination a 'platform', here's an overview of currently defined arch.flags per platform:


GNU-Linux armv6l:
arch.flags = -march=armv6 -mfpu=vfp -mfloat-abi=hard

GNU-Linux armv7l:
arch.flags = -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard

GNU-Linux i386, i686:
arch.flags = -march=pentium4 -mfpmath=sse -msse -msse2

GNU-Linux ia64, x86_64:
arch.flags = -march=core2 -mfpmath=sse -msse -msse2 -msse3

Darwin i386:
arch.flags := -arch ppc -arch i386 -arch x86_64 -mmacosx-version-min=10.4

Darwin x86_64:
arch.flags := -arch i386 -arch x86_64 -mmacosx-version-min=10.5

Windows:
arch.flags := -march=pentium4 -msse -msse2 -mfpmath=sse


The '-arch' options clearly refer to CPU architecture. I think the '-m' options refer to 'machine' which may mean CPU plus co-processors or other hardware. But what about '-mmacosx-version-min' then? GCC docs classify this under 'Darwin Options', which in turn is a section in 'Hardware Models and Configuration':

https://gcc.gnu.org/onlinedocs/gcc/Darwin-Options.html#Darwin-Options

The Darwin Options 'are defined for all architectures running the Darwin operating system'. Option '-mmacosx-version-min' can set the earliest version of MacOS X that the executable will run on. So the option is about OS, yet it is an -m (machine?) option. It makes the category of -m flags ambiguous, and with that it makes Makefile.pdlibbuilder's arch.flags ambiguous. Since renaming arch.flags into something like platform.flags can't take away that ambiguity we'll have to live with it I guess.

Now the question is how to split arch.flags for compiler and linker. I think (but don't know for sure) these options are for compiler only:

-march
-mfpu
-mfloat-abi
-mfpmath
-msse
-msse2
-msse3

And these options for compiler and linker (applicable for OSX):
-arch
-mmacosx-version-min

If this can be confirmed I'll reorganize these options accordingly in categories arch.c.flags and arch.ld.flags and make these overridable by CFLAGS resp. LDFLAGS.

**Comment by katjav** [comment] 2015-12-05 10:59
In branch 'command-line-build-flags' the accumulation of build flags is reorganized in such a way that all non-essential build flags can be overriden by CFLAGS and LDFLAGS from command line or environment. This includes flags that build for or tune to specific architectures. I've also added CPPFLAGS for additional preprocessor flags to make the set complete.

It works for me on Linux in a preliminary test. But it needs some real-world testing (on 'all' platforms) to make sure it works as intended.

**Comment by katjav** [comment] 2015-12-06 19:30
After a small fix today, branch 'command-line-build-flags' seems to work fine on OSX as well. If the puredata package maintainer is happy with it too I would merge it into the main line.

**Comment by umlaeute** [comment] 2015-12-21 09:49
ah sorry, it seems you are waiting for an answer from my side. just a second.

**Comment by umlaeute** [comment] 2015-12-21 10:59
did a check and it seems that all is well on my side (I see some issues but they seem to be unrelated to Makefile.pdlibbuilder)

**Comment by katjav** [comment] 2015-12-27 21:47
I felt compelled to do a bit of regression testing on Windows before merging. All seems right and branch command-line-build-flags is merged into master with commit  98f3582, version 0.2.1.

**Comment by katjav** [comment] 2015-12-28 08:08
Deleted test branch command-line-build-flags

**Comment by umlaeute** [comment] 2016-02-04 21:16
afaik this ticket has been resolved.

**Closed** 2016-02-11 08:38 UTC
