### ISSUE TITLE
fails to build else/plaits~ with Pd 0.55

### ISSUE THREAD

**Issue by porres** [pure-data/pd-lib-builder#81] opened 2024-06-02 15:47 UTC
Not sure what happens but I upgraded to pd-lib-builder 0.7 and now I can't compile plaits~ (see https://github.com/porres/pd-else/blob/master/Code_source/Compiled/audio/plaits~/plaits~.cpp )

I get 

```
plaits~.cpp:471:5: error: expected ';' at end of declaration list
/Applications/Pd-0.55-0test3a.app/Contents/Resources/src/m_pd.h:575:69: note: 
      expanded from macro 'CLASS_MAINSIGNALIN'
    STATIC_ASSERT(sizeof(((type *)NULL)->field) == sizeof(t_float), "field m...
                                                                    ^
plaits~.cpp:471:5: warning: offset of on non-POD type 't_plaits' (aka '_plaits')
      [-Winvalid-offsetof]
    CLASS_MAINSIGNALIN(plaits_class, t_plaits, x_f);
```

It's weird cause "x_f" IS t_float, and it all compiles fine if I use pd-lib-builder 0.6 or againt's Pd's 0.54-1 m_pd.h file

So it seems Pd has changed m_pd.h and pd-lib-builder needs to be worked out and updated as well? Or can we "fix" things in Pd 0.55?

**Comment by Spacechild1** [comment] 2024-06-02 22:26
I changed the `CLASS_MAINSIGNALIN` macro to use the standard `offsetof` instead of the non-standard NULL pointer cast trick.

There are a few caveats regarding C++:
https://en.cppreference.com/w/cpp/types/offsetof

Specifically: 

> If type is not a [PODType](https://en.cppreference.com/w/cpp/named_req/PODType)(until C++11)[standard-layout](https://en.cppreference.com/w/cpp/language/data_members#Standard-layout) type(since C++11), the result of offsetof is undefined(until C++17)use of the offsetof macro is conditionally-supported(since C++17).

The fact that your compiler complains about *non-POD types* suggests that you are compiling in C++98 mode (for whatever reason). All modern compilers default to C++11 or higher.

That being said, a warning is just a warning. The actual error is this:
> `plaits~.cpp:471:5: error: expected ';' at end of declaration list`

I have no idea what is happening there and how it would be caused by `offsetof`...

Anyway, I can successfully build the latest master branch of else (https://github.com/porres/pd-else/commit/ad56f5ae9c0fb516883b62f658992ad52ec4fb1e) with g++ (Msys2)  against the Pd-0.55 `m_pd.h` header. Same for my own C++ externals (which are certainly not PODs) with MSVC, g++ (Msys2) and AppleClang.

Your CI pipeline seems to work, though. Is this only a problem on your machine? What is your compiler (version)?

**Comment by Spacechild1** [comment] 2024-06-02 22:52
I just made a little test program:

```
#include <vector>
#include <iostream>

#include "m_pd.h"

class Foo {
public:
    Foo() {}
    ~Foo() {}

    std::vector<float> vec;
    float f;
};

int main() {
    t_class *c = NULL;

    CLASS_MAINSIGNALIN(c, Foo, f);

    return 0;
}
```

With g++ I cannot get a warning even when I compile with `-std=c++98 -Wall -Wextra`.

With clang I can reproduce the warning with `clang++ -c -I<PD>/src -Wall -Wextra -std=c++98 offsetof_test.cpp`:
```
offsetof_test.cpp:18:5: warning: offset of on non-POD type 'Foo' [-Winvalid-offsetof]
    CLASS_MAINSIGNALIN(c, Foo, f);
    ^                          ~
C:/Repos/pure-data/src/m_pd.h:576:29: note: expanded from macro 'CLASS_MAINSIGNALIN'
    class_domainsignalin(c, offsetof(type, field))
                            ^              ~~~~~
C:/msys64/clang64/lib/clang/15.0.5/include/stddef.h:104:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
1 warning generated.
```

Note that it still compiles successfully!

**Comment by umlaeute** [comment] 2024-06-03 07:06
> All modern compilers default to C++11 or higher.

i think @porres is developing on a rather old system (which is not a bad thing), and thus might **not** have a *modern* compiler. (unfortunately we know neither the macOS version, nor the compiler version nor the actual invocation of the compiler).

(I was briefly tempted to try to build myself on one of my macOS systems, but after seeing the sheer size of the repository and the included binaries, i decided that it is not worth my time)

**Comment by porres** [comment] 2024-06-03 07:26
yup, I'm on a 2013 macbook air with mojave 10.14.6, so kind old :)

**Comment by Spacechild1** [comment] 2024-06-03 07:44
> but after seeing the sheer size of the repository and the included binaries, i decided that it is not worth my time

@umlaeute It actually builds rather quickly on my MacBook.

> yup, I'm on a 2013 macbook air with mojave 10.14.6, so kind old :)

@porres So your C++ compiler might still default to C++98. But then again, I tried to explicitly build with `-std=c++98 -Wall -Werror` and although I get the same warning, I get no *error*. The error message you get just doesn't make any sense... I think this is really a problem with your old AppleClang.

What happens when you add `-std=c++11` to `cflags` in the plaits~ Makefile?

**Comment by Spacechild1** [comment] 2024-06-03 08:31
Hah! I just realized that else doesn't build `plaits~` by default and I have to do `make plaits`. Now I actually get the error!

Turns out that it has nothing to do with `offsetof`! The problem is that some header in the plaits code base defines its own (incompatible) `STATIC_ASSERT` macro, which is then accidentally used in `CLASS_MAINSIGNALIN`.

I simply renamed `STATIC_ASSERT` to `PD_STATIC_ASSERT` and now it works. I just pushed a fix to develop. @porres Can you try with the lastest develop branch?

Lesson learned: *always* prefix your symbols! (I don't know why I forgot it in this case...)

**Closed as completed** 2024-06-07 21:42 UTC
